version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: echodevnewsletter_db
    restart: always
    environment:
      POSTGRES_DB: echodevnewsletter
      POSTGRES_USER: root
      POSTGRES_PASSWORD: jkmv9004
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: ./backend
    container_name: echodevnewsletter_app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/echodevnewsletter
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: jkmv9004
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend/echodev-newsletter-frontend
    container_name: echodevnewsletter_frontend
    depends_on:
      - app
    ports:
      - "3000:80"

volumes:
  postgres_data: